fix: in tutor plugin's webpack config, fix `fs` double declaration
The mfe-webpack-dev-config tries to define `const fs`, even though
that constant is already defined at the top of the file.

Fixes this error, from `tutor dev dc build`:

    > fedx-scripts webpack-dev-server --progress "--config" "./webpack.dev-tutor.config.js"

    [webpack-cli] Failed to load '/openedx/app/webpack.dev-tutor.config.js' config
    [webpack-cli] /openedx/app/webpack.dev-tutor.config.js:24
    const fs = require('fs');
	  ^

    SyntaxError: Identifier 'fs' has already been declared